site_name: CIEL-IR-Rascol
repo_url: https://github.com/ciel-ir-rascol/ciel-ir-rascol.github.io
repo_name: ciel-ir-rascol.github.io
theme:
  language: fr
  favicon: assets/logo.png
  icon:
    logo: octicons/code-review-16
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - content.code.annotate
    - content.code.copy
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary : indigo
      accent : indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary : indigo
      accent : indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

copyright: Ce site ainsi que tout son contenu est mis à disposition selon les termes de la <a href="https://creativecommons.org/licenses/by/4.0/">Licence Creative Commons Attribution 4.0 International</a>.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home : index.md
  - C++ :
    - Introduction : cpp/01-IntroCpp/introCpp.md
    - Utilisation IDE : cpp/02-utilisationIDE/utilisationIDE.md
    - Variables et Constantes : cpp/03-variablesConstantes/variablesConstantes.md
    - Tableaux et vecteurs : cpp/04-tableauxVecteurs/tableauxVecteurs.md
    - Structures sélectives : cpp/05-structuresSelectives/structuresSelectives.md
    - Structures itératives : cpp/06-structuresIteratives/structuresIteratives.md
    - Pointeurs : cpp/10-pointeurs/pointeurs.md
    - Classes et Objets : cpp/11-classesObjets/classesObjets.md
    - Constructeurs et Destructeurs : cpp/12-constructeursDestructeurs/constructeursDestructeurs.md
  - Linux :
    - Cours :
      - Introduction : linux/01-Intro.md
      # - Raspberry Pi : linux/02-Raspberry_pi.md
      - Commandes Bash : linux/03-Commandes_bash.md
      - Permissions : linux/04-Permissions.md
      # - Scripts Bash : linux/05-Scripts_bash.md
    - Activités :
      - ACT01 Terminal : linux/ACT1-Util_term.md
      - ACT02 Réseau : linux/ACT2-Linux_reseau.md
      - ACT03 Permissions : linux/ACT3-gerer_permissions.md    
  - Arduino : arduino/index.md
